name: Check Timer Script

on:
  pull_request:
    branches: [ "main" ]

  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: >-
            check_systemd_service.sh
        env:
          SHELLCHECK_OPTS: -s bash -f gcc -o all
