---
name: Run ShellCheck
run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

